### ISSUE TITLE
test poll

### ISSUE THREAD

**Issue by AxlAlm** [GU-CLASP/language-and-perception#1]
/polls alt1 alt2

**Comment by mmehdig** [comment]
Generate the HTML/Mardown here:
https://app.gh-polls.com/

Then paste the code in Markdown.

[![](https://api.gh-polls.com/poll/01EX76H9ZC6R5ASWRKD4KC71FT/a1)](https://api.gh-polls.com/poll/01EX76H9ZC6R5ASWRKD4KC71FT/a1/vote)
[![](https://api.gh-polls.com/poll/01EX76H9ZC6R5ASWRKD4KC71FT/a2)](https://api.gh-polls.com/poll/01EX76H9ZC6R5ASWRKD4KC71FT/a2/vote)
[![](https://api.gh-polls.com/poll/01EX76H9ZC6R5ASWRKD4KC71FT/a3)](https://api.gh-polls.com/poll/01EX76H9ZC6R5ASWRKD4KC71FT/a3/vote)
[![](https://api.gh-polls.com/poll/01EX76H9ZC6R5ASWRKD4KC71FT/a4)](https://api.gh-polls.com/poll/01EX76H9ZC6R5ASWRKD4KC71FT/a4/vote)

**Comment by mmehdig** [comment]
[![](https://api.gh-polls.com/poll/01EX76H9ZC6R5ASWRKD4KC71FT/new-option)](https://api.gh-polls.com/poll/01EX76H9ZC6R5ASWRKD4KC71FT/new-option/vote)
